### ISSUE TITLE
Do you plan to make it works with awesome 4.0 

### ISSUE THREAD

**Issue by jorgemota** [pw4ever/awesome-wm-config#8] opened 2017-01-20 18:15 UTC
I am trying to fix your rc.lua with awesome 4.0 (Released today on arch) but give random errors every time I fixed something >.< and I am wondering if you are going to upgrade :D

**Comment by pw4ever** [comment] 2017-01-20 19:48
@jorgemota Thanks for the heads up. I think I got work to do after my next "pacman -Syu".

**Comment by jorgemota** [comment] 2017-01-20 19:56
thanks man! I am using your configuraton, and I liked it :D :dancer:

**Comment by pw4ever** [comment] 2017-01-20 20:45
Thanks for letting me know. Glad you find it useful :)

Will close this issue after making it compatible with Awesome 4.0.

**Comment by jorgemota** [comment] 2017-01-20 21:25
Ok, by the way, my first problem was referenced to https://github.com/awesomeWM/awesome/issues/244

 after pacman -Syyuu,  in /usr/share/awesome/lib exists folder **beautify** and **beautiful.lua** and awesome got crazy and throws a lot of errors about textbox, widget, etc, removing beautiful.lua let me work with your configuration up 40% (before was at 5% >.<)

**Comment by pw4ever** [comment] 2017-01-21 08:23
@jorgemota I don't think Awesome 4.0 is stable enough to be moved to.

I have fixed errors due to non-backward-compatible API changes (e.g., with regard to mouse.screen => awful.screen.focused() etc.).

However, I run into the following internal errors with awful.prompt:

> /usr/share/awesome/lib/awful/prompt.lua:408: attempt to call a nil value (method 'set_font')

This error is caused by textbox widget's "set_font" method being replaced by "font" property (perhaps in the "expose data not accessor" anti-unnecessary-encapsulation philosophy as in Clojure, which I agree with), without providing a shim for the older accessor. This is quite disrupting.

So it appears that the API change in Awesome 4.0 has caused issues even for its own inbox library.

For now, I am downgrading to the perfectly working v3.5.9, and have added "awesome" to my pacman.conf IgnorePkg list. I will consider moving to v4.x when 4.x is stable enough.

My work-in-progress changes is here: https://github.com/pw4ever/awesome-wm-config/tree/next-4.x

**Comment by jorgemota** [comment] 2017-01-21 16:09
OH.. I am going to downgrade too  thanks for your works.

**Comment by jorgemota** [comment] 2017-01-21 18:08
I got working awesome again with your version, only commented all body function update_textbox on uniargs. and no more errors :)

**Comment by jorgemota** [comment] 2017-01-22 03:56
Using awesome-git and the rc.lua from  https://github.com/pw4ever/awesome-wm-config/tree/next-4.x

I needed to edit uniargs.lua and remove body method for update_texbox function.

Last thing I needed to change in rc.lua was this:

[[awful.key({modkey}, "r", function()
    awful.prompt.run(
    {prompt = "Run: "},
    **customization.widgets.promptbox[awful.screen.focused().index],**
    awful.util.spawn, awful.completion.shell,
    awful.util.getdir("cache") .. "/history"
    )
end),

Changed to: (same function used in Modkey + f2 )
awful.key({modkey}, "r", function()
    awful.prompt.run(
    {prompt = "Run: "},
    **customization.widgets.promptbox[awful.screen.focused().index].widget,**
    awful.util.spawn, awful.completion.shell,
    awful.util.getdir("cache") .. "/history"
    )
end),

And now I don't get any error anymore :dagger:

**Comment by pw4ever** [comment] 2017-01-23 02:22
@jorgemota 
I have released [an update that is compatible with Awesome 4.0 (at least in my local test)](https://github.com/pw4ever/awesome-wm-config/tree/awesome-4.x).

Please give it a try and let me know if it also works for you.

**Comment by jorgemota** [comment] 2017-01-23 03:27
Nice work, , moved to branch I am going to test it tomorrow, thanks for the changes. first tests don't show any error.

**Comment by pw4ever** [comment] 2017-01-23 08:03
@jorgemota Had some new updates with regard to multi-screen support. Please git-pull and test the latest version (4.0.1). Thanks!

**Comment by pw4ever** [comment] 2017-01-23 08:16
@jorgemota Latest one is 4.0.2, with client rules update.

**Comment by jorgemota** [comment] 2017-01-23 14:30
Updated to 4.0.2 and I lost the systray for icons. Skype, pidgin, nm-applet is not showing icon in systray :(

**Comment by pw4ever** [comment] 2017-01-23 18:47
@jorgemota 
Thanks for catching the bug. Should be fixed now in 4.0.3.

**Comment by jorgemota** [comment] 2017-01-23 20:13
Hi @pw4ever  I don't see any commit or changes :)

**Comment by pw4ever** [comment] 2017-01-23 20:55
@jorgemota 
My apologies. Messed up git-pushing. Now should fixed.
Thanks for the patience :)

**Comment by jorgemota** [comment] 2017-01-23 20:57
thanks to you! I got back my old systray with this commit !

**Comment by jorgemota** [comment] 2017-01-23 20:58
I am wondering, can you please add some file or properties file (External to avoid rewrite on update), to read if user want cpu, battery, and mdp? every time I update lost my customization on date format, removed cpu/memory and I dont use mdp :P  thanks for all the work man.

**Comment by pw4ever** [comment] 2017-01-23 21:22
@jorgemota 
For this specific use case, I would recommend you clone the repo and create a local-jorgemota-4.x branch (like my local-1pengw-4.x branch) that have your customization.

Then when you pull a new awesome-4.x branch, you can just:
```
git checkout local-jorgemota-4.x
git merge awesome-4.x
```
which will port your customization forward. This is what I have been doing so far.

**Comment by jorgemota** [comment] 2017-01-23 21:23
ohh, I will give this a try.  Thanks man.

**Comment by pw4ever** [comment] 2017-01-23 21:24
@jorgemota I will close this issue for now. Thanks for testing this out!

**Closed as completed by pw4ever** 2017-01-23 21:24 UTC
